# Site Settings
title: Daan Geerdink
email: daangeerdink@live.nl
description: Portfolio and personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://daangeerdink.nl" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Daan Geerdink
user_description: Dutch ğŸ‡³ğŸ‡± | Videographer ğŸ“· | Gymnast ğŸ… | MSc student Chemical Engineering at Delft University of Technology ğŸ‘¨â€ğŸ”¬.

# Social Media
# Remove the item if you don't need it
github_username: dfgeerdink
instagram_username: daangeerdink
linkedin_username: daan-geerdink

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About Me
    url: /about/
  - title: Blog Categories
    url: /category/
  - title: Business & Collaborations
    url: /business/
  - title: Contact
    url: /contact/

# Banner
banner: bannermain.mp4
banner-title: "Low Key Creativity"
banner-desc1: "Exploring aestetics in: Videography"
banner-desc2: "Exploring aestetics in: Travel"
banner-desc3: "Exploring aestetics in: Coding"
banner-desc4: "Exploring aestetics in: Technology"

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
