# Site Settings
title: Daan Geerdink
email: daangeerdink@live.nl
description: Portfolio and personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://daangeerdink.nl" # the base hostname & protocol for your site
google_analytics: "UA-126427192-1"

# User Settings
username: Daan Geerdink
user_description: Dutch ğŸ‡³ğŸ‡± | Chemical Engineer & Consultant Hydrogen Technology at DNV ğŸ‘¨â€ğŸ”¬.

# Social Media
# Remove the item if you don't need it
github_username: dfgeerdink
instagram_username: daangeerdink
linkedin_username: daan-geerdink

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About Me
    url: /about/
  - title: Blog Categories
    url: /category/

# Banner
banner: bannermain.mp4
banner-title: "Curiosity"
banner-desc1: "Exploring: Videography"
banner-desc2: "Exploring: Travel"
banner-desc3: "Exploring: Programming"
banner-desc4: "Exploring: Technology"

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
